IT_Project/it_project/urls.py
from django.contrib import admin
from django.urls import path, include

from locations import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('locations.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
    # path('register/', views.register),
    # path('login/', views.login),
]

IT_Project/locations/urls.py
from django.urls import path
# from .views import LocationView
from locations import views

app_name = 'locations'

urlpatterns = [
    path('', views.index, name='index'),
    # path('vehicle/', views.index, name='vehicle'),
    path('order_history/', views.order_history,name='order_history'),
    path('order_history/<int:nid>/details/', views.order_detail, name = 'order_detail'),
    path('create_order/', views.create_order, name='create_order'),
    path('return_order/', views.return_order, name='return_order'),
    path('conclude_order/', views.conclude_order, name='conclude_order'),
    path('deposit/', views.deposit, name='deposit'),
    path('order_history/<int:nid>/payment/', views.payment, name = 'order_payment'),
    path('payment/<int:nid>/', views.payment, name='payment'),
]

IT_Project/locations/models.py
from django.db import models
import geocoder
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User

# IMPORTANT!
# Models are not finished!

MAPBOX_ACCESS_TOKEN = 'pk.eyJ1IjoiYWxlc3NpbzIxIiwiYSI6ImNsZWszb2twMzBoa3QzcHBnNnhqbHIwMHUifQ.AW2-2b4IYh4qqPqqzMXy8Q'

class Location(models.Model):
    address = models.TextField(unique=True)
    latitude = models.FloatField(blank = True, null = True)
    longitude = models.FloatField(blank = True, null = True)

    def save(self, *args, **kwargs):
        #Get the geocoder object relative to the provided address
        bbox = [55.75, -4.5, 55.95, -3.9]
        # lat lng lat lng
        # bbox = [-4.5, 55.75, -3.9, 56]
        g = geocoder.mapbox(self.address, proximity = [55.75, -4.5], key = MAPBOX_ACCESS_TOKEN)
        #Get the longitude and latitude of the location
        g = g.latlng 
        self.latitude, self.longitude = g[0], g[1]
        return super(Location, self).save(*args, **kwargs)

class CustomUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=6, decimal_places=2,default=10.00)

    # def is_an_operator(self):
    #     return self.is_operator

    def is_a_customer(self):
        return not self.is_operator
    
    def __str__(self):
        return self.username

class VehicleType(models.Model):
    name = models.CharField(max_length=10, unique=True)
    cost_per_minute_in_cent = models.IntegerField(default= 30)
    cost_for_initial_order = models.IntegerField(default = 50)
    def __str__(self):
        return self.name
    
class Vehicle(models.Model):
    type = models.ForeignKey(VehicleType, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.DO_NOTHING)
    is_available = models.BooleanField(default=True)
    
class Order(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    initial_time = models.DateTimeField(auto_now_add=True)
    cost = models.DecimalField(max_digits=6, decimal_places=2, null = True, default=None)
    final_time = models.DateTimeField(null = True)
    initial_location = models.ForeignKey(Location, on_delete=models.CASCADE, null=False, related_name='start')
    final_location = models.ForeignKey(Location, on_delete=models.CASCADE, null=True, related_name='end')
    is_paid = models.BooleanField(default=False)

class ReportType(models.Model):
    report_type = models.TextField(max_length="63", default="Other issues")

class Report(models.Model):
    text = models.TextField(max_length="255")
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    report_type = models.ForeignKey(ReportType, on_delete=models.DO_NOTHING, null=True)


IT_Project/locations/forms.py
# from django import forms
# from registration.forms import RegistrationForm
# from .models import CustomUser

# class CustomUserRegistrationForm(RegistrationForm):


#     def save(self, *args, **kwargs):
#         user = super().save(*args, **kwargs)
#         custom_user = CustomUser.objects.create(user=user)
#         return user

IT_Project/locations/views.py
import datetime
import json
import sqlite3
from django.contrib import messages
from django.views.generic.edit import CreateView
from decimal import Decimal

from . import models
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login
from django.http import JsonResponse
from .models import Vehicle, Order, Location, CustomUser, User, VehicleType



from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404

# Create your views here.
# Persona acess token to use mapbox
ACCESS_TOKEN_MAPBOX = 'pk.eyJ1IjoiYWxlc3NpbzIxIiwiYSI6ImNsZWszb2twMzBoa3QzcHBnNnhqbHIwMHUifQ.AW2-2b4IYh4qqPqqzMXy8Q'

# View to start a new order
def index(request):
    locations_with_bikes = Location.objects.filter(vehicle__type__name='Bike', vehicle__is_available = True).distinct() #  all locations that have at least one bike
    locations_with_scooters = Location.objects.filter(vehicle__type__name='Scooter', vehicle__is_available = True).distinct() # all locations that have at least one scooter
    bike = VehicleType.objects.get(name = "Bike")
    scooter = VehicleType.objects.get(name = "Scooter")

    # Pass data to web page through context
    context = {}
    context['locations_with_bikes'] = locations_with_bikes 
    context['locations_with_scooters'] = locations_with_scooters
    context['mapbox_access_token'] = ACCESS_TOKEN_MAPBOX # Mapbox token necessary to use map
    context['bike'] = bike
    context['scooter'] = scooter

    return render(request, 'locations/home.html', context=context)

def return_order(request):
    # If user is not logged in, redirect them
    if request.user is None or not request.user.is_authenticated:
        return redirect("/accounts/login")
    
    # Get customer
    username = request.user.username
    logged_user  = CustomUser.objects.get(user = User.objects.get(username = username))
    # Get order
    unreturned_order = Order.objects.filter(customer = logged_user, final_time = None).first()

    #Pass data to web page through context
    context = {}
    context['order_id'] = unreturned_order.id # Id of the order
    context['initial_time'] = unreturned_order.initial_time.strftime('%Y-%m-%d %H:%M:%S') # Initial time parsed as String
    context['cost_per_minute'] = unreturned_order.vehicle.type.cost_per_minute_in_cent # Cost per minute of the vehicle
    context['cost_for_initial_order'] = unreturned_order.vehicle.type.cost_for_initial_order # Initial cost of renting that vehicle
    context['mapbox_access_token'] = ACCESS_TOKEN_MAPBOX  # Mapbox token necessary to use map
    context['locations'] = Location.objects.all() # All locations

    return render(request, 'locations/return.html', context=context)

def order_history(request):
    if request.user is None or not request.user.is_authenticated:
        return redirect("/accounts/login")

    username = request.user.username
    logged_customer = CustomUser.objects.get(user=User.objects.get(username=username))
    queryset = models.Order.objects.filter(customer=logged_customer).order_by('id').reverse()

    return render(request, 'locations/order_history.html', {'queryset': queryset})

def order_detail(request,nid):
    #If user it not authenticated, redirect to login
    if request.user is None or not request.user.is_authenticated:
        return redirect("/accounts/login")
    #Get data
    order = models.Order.objects.get(id=nid)
    vehicle = order.vehicle.type.name
    date = order.initial_time.date()
    # Calculate duration
    return_time = order.final_time.strftime("%H:%M")
    timedelta = order.final_time - order.initial_time
    hours, remainder = divmod(timedelta.seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    formatted_time = f"{hours:02d}:{minutes:02d}:{seconds:02d}"

    cost = order.cost
    # From ---> to
    initial_address = order.initial_location.address
    final_address = order.final_location.address
    # If not the same customer, redirect
    if order.customer.user != request.user:
        return redirect("/order_history/")

    obj={'vehicle': vehicle , 'order_id':nid, 'date': date , 'returntime':return_time , 'formatted_time': formatted_time , 'cost':cost , 'iadd':initial_address , 'fadd':final_address, 'is_paid': order.is_paid}

    return render(request, 'locations/order_detail.html', {'obj': obj})

# Create new order given data from user
def create_order(request):
    # Redirect if not a post
    if request.method != 'POST':
        return render(request, 'locations/home.html')
    # Get data from json
    data = json.loads(request.body)
    username = data['username']
    vehicle_type = data['vehicle_type']
    loc_id = data['loc_id']

    # Get customer, locations and update vehicle's availability
    user = CustomUser.objects.get(user = User.objects.get(username = username))
    location = Location.objects.get(id=loc_id)
    vehicle = Vehicle.objects.filter(is_available = True, location=location, type = VehicleType.objects.get(name = vehicle_type)).order_by('id').first()
    vehicle.is_available = False
    vehicle.save()

    # Create order
    order = Order.objects.create(
        customer = user,
        vehicle = vehicle,
        initial_location = location
    )
    # Succesful response
    return JsonResponse({'status': 'success'})

# Terminate order and update fields
def conclude_order(request):
    # If not a post, redirect
    if request.method != 'POST':
        return render(request, '{locations:return_order}')
    # Get data from JSON
    data = json.loads(request.body)
    loc_id = data['loc_id']
    order_id = data['order_id']
    order = Order.objects.get(id = order_id)

    # Get vehicle and update location and availability
    used_vehicle = order.vehicle
    used_vehicle.is_available = True
    used_vehicle.location = Location.objects.get(id = loc_id)
    used_vehicle.save()

    # Add order location and final time
    order.final_location = Location.objects.get(id = loc_id)
    order.final_time = datetime.datetime.now()

    # Calculate duration and cost
    duration = order.final_time - order.initial_time
    duration_in_seconds = duration.total_seconds()
    duration_in_minutes = int(duration_in_seconds / 60)
    order.cost = (duration_in_minutes * order.vehicle.type.cost_per_minute_in_cent + order.vehicle.type.cost_for_initial_order) / 100

    # Save
    order.save()

    return JsonResponse({'status': 'success'})


def deposit(request):
    #If user is logged in
    if request.user is None or not request.user.is_authenticated:
        return redirect("/accounts/login")
    username = request.user.username
    logged_customer = CustomUser.objects.get(user=User.objects.get(username=username))
    # If button clicked
    if request.method == "POST":
        depositAmount = Decimal(request.POST.get("depositAmount"))
        logged_customer.balance += depositAmount
        logged_customer.save()
        return redirect("/order_history/")
    else:
        context = {}
        context['customer'] = logged_customer
        return render(request, "locations/deposit.html", context = context)
    

def payment(request,nid):
    #If user is not logged in, redirect
    if request.user is None or not request.user.is_authenticated:
        return redirect("/accounts/login")

    username = request.user.username
    logged_customer = CustomUser.objects.get(user=User.objects.get(username=username))
    balance = logged_customer.balance
    order = models.Order.objects.get(id=nid)
    cost=order.cost
    # Update balance
    if request.method == "POST":
        if(balance>cost):
            order.is_paid=1
            order.save()
            logged_customer.balance -= cost
            logged_customer.save()
            return redirect("/order_history/")
        else:
            return redirect("/deposit/")
    # If paid, go to order history
    if order.is_paid:
       return redirect("/order_history/")
    
    if order.customer.user.username != logged_customer.user.username:
        return redirect("/order_history/")

    context={'balance':balance , 'cost':cost, 'order': order}

    return render(request, "locations/payment.html", context)

IT_Project/templates/locations/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> V-Share {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}">
    {% block extrahead %}
    {% endblock %}
</head>
<body>
        <div class="navbar">
        {% if unreturned %}
        <a href="{% url 'locations:return_order' %}" class = "important"> Return a vehicle</a>
        {% else %}
        <a href="{% url 'locations:index' %}"> Rent a vehicle</a>
        {% endif %}

        {% if user.is_authenticated %}
        <a href="{% url 'auth_logout' %}?next=/" class = "authentication">Logout</a>

        <a href="{% url 'locations:order_history' %}">Order History</a>
        <a href="{% url 'locations:deposit' %}"> Top-up </a>
        {% else %}
        <a href="{% url 'auth_login' %}" class = "authentication" >Login</a>


        <a href="{% url 'registration_register' %}" class = "authentication"> Sign up </a>
        {% endif %}

    </div>

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    {% comment %} {% block scripts %} {% endblock %} {% endcomment %}

</body>
</html>

IT_Project/templates/locations/deposit.html
{% extends "locations/base.html" %}
{% load static %}

{% block title %} Deposit {% endblock %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/deposit.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/map.css' %}">

{% endblock%}
{% block content %}

<p id="price"> Balance: 💳 £{{ customer.balance}}</p>

  <div class="input-group">
    <form  method="POST" >
      {% csrf_token %}
    <input type="text" class="form-control" placeholder="5.00" aria-describedby="basic-addon2" style="width:160px; height:25px;" name="depositAmount">
    <button type="submit" name="deposit" id="deposit" value="none">Deposit</button>
    </form>
  </div>

{% endblock %}

IT_Project/templates/locations/home.html
{% extends "locations/base.html" %}
{% load static %}

{% block title %} Rent a vehicle {% endblock %}

{% block extrahead %}
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/map.css' %}">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css" rel="stylesheet">

    <script src="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js"></script>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js">
    </script>
    <script src='https://unpkg.com/@turf/turf/turf.min.js'></script>
    <link rel="stylesheet"
    href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css"
    type="text/css">
    
    {% comment %} Store variables from context here {% endcomment %}
    <script>  
        var locations = [];
        username = '{{user.username}}'
        
        var locations_with_bikes = [];
        {% for loc in locations_with_bikes %}
        locations_with_bikes.push({longitude: {{loc.longitude}}, latitude: {{loc.latitude}}, address:'{{loc.address}}', id:'{{loc.id}}'})
        {% endfor %}  
    
        var locations_with_scooters = [];
        {% for loc in locations_with_scooters %}
        locations_with_scooters.push({longitude: {{loc.longitude}}, latitude: {{loc.latitude}}, address:'{{loc.address}}', id:'{{loc.id}}'})
        {% endfor %}
        
        bike_cost = {{ bike.cost_per_minute_in_cent }}
        bike_service_fee = {{bike.cost_for_initial_order}}
        scooter_cost = {{ scooter.cost_per_minute_in_cent}}
        scooter_service_fee = {{scooter.cost_for_initial_order}}
        access_token = '{{ mapbox_access_token }}'
        success_url = "{% url 'locations:return_order' %}"
        login_url = "{% url 'auth_login' %}"
    </script>

{% endblock %}

{% block content %}
    
    <h1> Select your desired vehicle 🚲/🛴 and rent a vehicle nearby 🗺️  </h1> 
    <div class="vehicle-selection">
        <img id="bike-icon" class="vehicle-icon" src="{% static 'images/bike.svg' %}" alt="Bike">
        <div>
            <p id = "service"> Service fee: $ </p>
            <p id = "cost"> Cost per Minute: $ </p>
        </div>
        <img id="scooter-icon" class="vehicle-icon" src="{% static 'images/scooter.svg' %}" alt="Scooter">
      </div>
<div id="map"></div>
<div class="container">
    
    <button id="search"> Find nearest vehicle</button> 
    {% if user.is_authenticated %}
    <button id="submit-button" onclick="createOrder()"> Start Renting</button>
    {% else %}
    <button id="submit-button" onclick="loginEvent()"> Login to rent! </button>
    {% endif %}
 </div>


 {% comment %} <script type="text/javascript" src="{% static 'js/map_script.js' %}"></script> {% endcomment %}
 <script type="text/javascript" src="{% static 'js/make_order.js' %}"></script>
 <script type="text/javascript" src="{% static 'js/map_common.js' %}"></script>



 {% endblock %}





 


IT_Project/templates/locations/order_detail.html
{% extends "locations/base.html" %}
{% load static %}

{% block title %} Order Details {% endblock %}
{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/order.css' %}">

{% endblock %}
{% block content %}

  <div>
      <div class="container">
        <div class="panel panel-default">
      <div class="panel-heading">Order details</div>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Vehicle </th>
            <th>Order #</th>
            <th>Day </th>
            <th>Time returned</th>
            <th>Duration </th>
            <th>Cost </th>
            <th>From </th>
            <th>To</th>
          </tr>
        </thead>
        <tbody>
          <tr>
             <td>{{ obj.vehicle }}</td>
             <td>{{ obj.order_id }}</td>
             <td>{{ obj.date }}</td>
             <td>{{ obj.returntime }}</td>
             <td>{{ obj.formatted_time }}</td>
             <td>{{ obj.cost }}   
              {% if obj.is_paid != True %}
              <a class="btn btn-primary btn-xs" href="{% url 'locations:order_payment' nid=obj.order_id %}"> PAY </a>
              {% endif %}
             </td>
             <td>{{ obj.iadd }}</td>
             <td>{{ obj.fadd }}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>


{% endblock %}

IT_Project/templates/locations/order_history.html
{% extends "locations/base.html" %}
{% load static %}

{% block title %}Order History{% endblock %}

{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/order.css' %}">

{% endblock %}

{% block content %}
  <div class="container">
    <div class="panel panel-default">
      <!-- Default panel contents -->
      <div class="panel-heading"> Order history</div>

      <!-- Table -->
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>order ID</th>
            <th> Rented on</th>
            <th> Returned at</th>
            <th> Cost (£) </th>
            <th> See more</th>
          </tr>
        </thead>
        <tbody>
        {% for obj in queryset %}
          <tr>
            <th>{{obj.id}}</th>
            <td>{{ obj.initial_time|date:"d M Y, H:i" }}</td>
            <td>{{ obj.final_time|date:"H:i" }}</td>
            {% if obj.is_paid %}
            <td class="cost"> {{ obj.cost}} </td>
            {% elif obj.cost != None %}
            <td> {{ obj.cost}} </td>
            {% else %}
            <td>  </td>

            {% endif %}
            <td>
              {% if obj.final_time != None%}
              <a class="btn btn-primary btn-xs" href="{% url 'locations:order_detail' nid=obj.id %}"> Details</a>
              {% else%}
              The orer must be terminated to see its details.
              {% endif %}
              {% if obj.is_paid %}
              {% else %}
              {% if obj.cost != None %}
              <a class="btn btn-primary btn-xs" href="{% url 'locations:order_payment' nid=obj.id %}"> PAY </a>
              {% endif %}
              {% endif %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

IT_Project/templates/locations/payment.html
{% extends "locations/base.html" %}
{% load static %}

{% block title %} Payment {% endblock %}


{% block extrahead %}
<link rel="stylesheet" type="text/css" href="{% static 'css/payment.css' %}">


{% endblock%}

{% block content %}
  <div class="content-wrapper">
    <div class="payment-info">
      <p>Your balance: ￡{{ balance }}</p>
      <p>You need to pay: ￡{{ cost }}</p>
      {% if balance < cost%}
      <p> Insufficient credit </p>
      {% endif%}
    </div>
    <div class="btn-wrapper">
      <form  method="POST" >
      {% csrf_token %}
      <a class="btn btn-primary btn-xs" href="{% url 'locations:order_detail' nid=order.id %}">See details for order #{{order.id}}</a>
      {% if balance < cost%}
      <a class="btn btn-primary btn-xs" href="{% url 'locations:deposit' %}"> Top up!</a>
      {% else %}
      <button class="btn btn-primary btn-xs" type="submit" name="pay" id="pay" value="none">Pay now</button>
      </form>


      {% endif%}

    </div>
  </div>

{% endblock %}

IT_Project/templates/locations/return.html
{% extends "locations/base.html" %}
{% load static %}

{% block title %} Return vehicle {% endblock %}

{% block extrahead %}
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/map.css' %}">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js"></script>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js">
    </script>
    <script src='https://unpkg.com/@turf/turf/turf.min.js'></script>
    <link rel="stylesheet"
    href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css"
    type="text/css">
    
    {% comment %} Needed to pass variables to the js script as js scripts do not have access to django objects {% endcomment %}
    <script>  
        var locations = [];
        {% for loc in locations %}
        locations.push({longitude: {{loc.longitude}}, latitude: {{loc.latitude}}, address:'{{loc.address}}', id:'{{loc.id}}'})
        {% endfor %}  
        username = '{{user.username}}'
    
        access_token = '{{ mapbox_access_token }}'

        // Order variables
        var datetimeString = "{{ initial_time }}";  // Get the datetime value from the Django object
        order_id = {{ order_id}}
        var cost_per_minute = {{ cost_per_minute}}
        var cost_for_initial_order = {{cost_for_initial_order}} 

        {% comment %} success_url = "{% url 'locations:order_history/1/details/' %}" {% endcomment %}
        success_url = "{% url 'locations:order_history' %}"
    </script>

{% endblock %}

{% block content %}
    
<h1> Return your vehicle at a nearby dedicated parking area </h1> 
<p id="timer"></p>
<p id="price"></p>


<div id="map"></div>
<div class="container">
    {% comment %} Store variables from context here {% endcomment %}
    
<button id="search"> Find Nearest Parking Area </button> 
    {% if user.is_authenticated %}
    <button id="submit-button" >Return </button>
    <!-- code for authenticated user -->
    {% else %}
        <h2> Register here! {{user.username}} </h2>
        <!-- code for unauthenticated user -->
    {% endif %}
 </div>


 <script type="text/javascript" src="{% static 'js/map_common.js' %}"></script>
 <script type="text/javascript" src="{% static 'js/return_order.js' %}"></script>

 {% endblock %}





 